#
# Buildbot only configs
#
buildbot:
    gcc:
        version: '14.2.1'
    xcode:
        version: '26.1.1'
    cuda10:
        version: '10.1.243'
    cuda11:
        version: '11.4.1'
    cuda12:
        version: '12.8.0'
    hip:
        windows:
            version: '6.4.2'
        linux:
            version: '6.4.3'
    optix:
        version: '8.0.0'
    ocloc:
        version: '101.8331'
    msvc:
        version: '2022'
        use_clang_cl: true
    cmake:
        default:
            version: any
            overrides: {}
        darwin-arm64:
            overrides: {}
        darwin-x86_64:
            overrides: {}
        linux-x86_64:
            overrides: {}
        windows-amd64:
            overrides: {}
        windows-arm64:
            overrides: {}
