#
# Used by Buildbot build pipeline make_update.py script only for now
# We intended to update the make_update.py in the branches to use this file eventually
#
update-code:
    git:
        submodules:
        -   branch: blender-v3.1-release
            commit_id: HEAD
            path: release/scripts/addons
        -   branch: blender-v3.1-release
            commit_id: HEAD
            path: release/scripts/addons_contrib
        -   branch: blender-v3.1-release
            commit_id: HEAD
            path: release/datafiles/locale
        -   branch: blender-v3.1-release
            commit_id: HEAD
            path: source/tools
    svn:
        libraries:
            darwin-arm64:
                branch: tags/blender-3.1-release
                commit_id: HEAD
                path: lib/darwin_arm64
            darwin-x86_64:
                branch: tags/blender-3.1-release
                commit_id: HEAD
                path: lib/darwin
            linux-x86_64:
                branch: tags/blender-3.1-release
                commit_id: HEAD
                path: lib/linux_centos7_x86_64
            windows-amd64:
                branch: tags/blender-3.1-release
                commit_id: HEAD
                path: lib/win64_vc15
        tests:
            branch: tags/blender-3.1-release
            commit_id: HEAD
            path: lib/tests
        benchmarks:
            branch: trunk
            commit_id: HEAD
            path: lib/benchmarks

#
# Buildbot only configs
#
buildbot:
    gcc:
        version: '9.0.0'
    cuda10:
        version: '10.1.243'
    cuda11:
        version: '11.4.1'
    optix:
        version: '7.3.0'
    cmake:
        default:
            version: any
            overrides: {}
        darwin-arm64:
            overrides: {}
        darwin-x86_64:
            overrides: {}
        linux-x86_64:
            overrides: {}
        windows-amd64:
            overrides: {}
