#
# Do NOT merge to master 
#

#
# Used by Buildbot build pipeline make_update.py script only for now
# We intended to udpate the make_update.py in the branches to use this file eventually
#
update-code:
    git:
        submodules:
        -   branch: blender-v2.83-release
            commit_id: HEAD
            path: release/scripts/addons
        -   branch: blender-v2.83-release
            commit_id: HEAD
            path: release/scripts/addons_contrib
        -   branch: blender-v2.83-release
            commit_id: HEAD
            path: release/datafiles/locale
        -   branch: blender-v2.83-release
            commit_id: HEAD
            path: source/tools
    svn:
        libraries:
            darwin-arm64:
                branch: tags/blender-2.83-release
                commit_id: HEAD
                path: lib/darwin_arm64
            darwin-x86_64:
                branch: tags/blender-2.83-release
                commit_id: HEAD
                path: lib/darwin
            linux-x86_64:
                branch: tags/blender-2.83-release
                commit_id: HEAD
                path: lib/linux_centos7_x86_64
            windows-amd64:
                branch: tags/blender-2.83-release
                commit_id: HEAD
                path: lib/win64_vc15
        tests:
            branch: tags/blender-2.83-release
            commit_id: HEAD
            path: lib/tests

#
# Buildbot only configs
#
buildbot:
    gcc:
        version: '9.0.0'
    cuda10:
        version: '10.1.0'
    cuda11:
        version: '11.4.0'
    optix:
        version: '7.0.0'
    cmake:
        default:
            overrides: {}
            version: any
        darwin-arm64:
            overrides: {}
        darwin-x86_64:
            overrides: {}
        linux-x86_64:
            overrides: {}
        windows-amd64:
            overrides: {}
