#
# Used by Buildbot build pipeline make_update.py script only for now
# We intended to update the make_update.py in the branches to use this file eventually
#
update-code:
    git:
        submodules:
        -   branch: master
            commit_id: HEAD
            path: release/scripts/addons
        -   branch: master
            commit_id: HEAD
            path: release/scripts/addons_contrib
        -   branch: master
            commit_id: HEAD
            path: release/datafiles/locale
        -   branch: master
            commit_id: HEAD
            path: source/tools
    svn:
        libraries:
            darwin-arm64:
                branch: trunk
                commit_id: HEAD
                path: lib/darwin_arm64
            darwin-x86_64:
                branch: trunk
                commit_id: HEAD
                path: lib/darwin
            linux-x86_64:
                branch: trunk
                commit_id: HEAD
                path: lib/linux_x86_64_glibc_228
            windows-amd64:
                branch: trunk
                commit_id: HEAD
                path: lib/win64_vc15
        tests:
            branch: trunk
            commit_id: HEAD
            path: lib/tests
        benchmarks:
            branch: trunk
            commit_id: HEAD
            path: lib/benchmarks

#
# Buildbot only configs
#
buildbot:
    gcc:
        version: '11.0.0'
    cuda10:
        version: '10.1.243'
    cuda11:
        version: '11.4.1'
    hip:
        version: '5.3.22480'
    optix:
        version: '7.3.0'
    ocloc:
        version: '101.3430'
    cmake:
        default:
            version: any
            overrides: {}
        darwin-arm64:
            overrides: {}
        darwin-x86_64:
            overrides: {}
        linux-x86_64:
            overrides: {}
        windows-amd64:
            overrides: {}
